---
apiVersion: v1
kind: Service
metadata:
  name: gad-service
  namespace: gad
  labels:
    k8s-app: gad-we-service
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "GadService"
spec:
  selector:
    k8s-app: gad-webserver
  ports:
  - name: gadweb
    port: 9001
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gad-ingress
  namespace: gad
spec:
  rules:
  - host: gad.clickyab.ae
    http:
      paths:
      - path: /
        backend:
          serviceName: gad-service
          servicePort: 9001